server:
  port: 8081
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_app_db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    password:
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: admin-app
    
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true